config/routes.rb
Resume::Application.routes.draw do
  get "sessions/new"

  get "sessions/create"

get   '/login', :to => 'sessions#new', :as => :login

  get "password_resets/new"

  resources :events

  resources :users
  resources :password_resets
  resources :sessions, only: [:new, :create, :destroy]
match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
   
  match '/create', to: 'events#new'
  match '/about', to: 'pages#about'
  match '/index' , to: 'events#index'
  match '/fanorona', to: 'pages#fanorona'
  match '/main_pro',to: 'pages#mainproject'
  match '/clipping',to: 'pages#clip'
  match '/contact', to: 'pages#contact'
  match '/qualifications' , to: 'pages#qualifications'
  match '/rails' , to: 'pages#rails'
  
  match 'auth/:provider/callback', to: 'sessions#create'
match 'auth/failure', to: redirect('sessions#failure')
match 'signout', to: 'sessions#destroy', as: 'signout'
match '/tamulol' , to: 'pages#tamulol'

  root :to => 'pages#home'

end

app/views/layouts/_header.html.erb
<script type="text/javascript" src="jquery-1.3.2.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
            $("body").css("display", "none");
            $("body").fadeIn(2000);
    });
</script>

<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Khoa's Online Resume", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
        	  
          
                    <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              	Projects
              	<b class="caret"></b>
              </a>
              	              <ul class="dropdown-menu">
                <li><%= link_to "C++", '#' %></li>
                                  
             
                 
                <li>  <%= link_to "Clipping", '/clipping' %></li>
                  
                   <!-- <li>    <%= link_to "Graphics2", '#' %>  </li> -->
              
            <li class="divider">
                <li><%= link_to "Java", '#' %></li>
                
                      </li>
                <li>
                  <%= link_to "Fanorona", '/fanorona' %>
                </li>
                    <li class="divider"> </li>
                <li> <%= link_to "Ruby on Rails", '#' %></li>
                
 				    <li>	<%= link_to "Khoa's Resume", '/rails' %></li>
 				    <li><%= link_to "TAMU Esports ", '/tamulol'%></li>
              </ul>
              	<li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              	About Khoa
              	<b class="caret"></b> </a>
              	<ul class="dropdown-menu">
          <li><%= link_to "About Khoa", '/about' %></li>
          <li><%= link_to "Contact Info", '/contact' %></li>
          <li><%= link_to "Qualifications", '/qualifications' %></li>
          
           </ul>
          <% if signed_in? %>
             <li><%= link_to "Send Message", '/create' %></li>
           <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Logged in as <%=   current_user.name %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li> <%= link_to "Send Message", '/create' %></li>
                
                  <li> <%= link_to "View Messages", '/index' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
                
              </ul>
            </li>
          <% else %>
          <li><%= link_to "Send Message", signin_path %></li>
           <!-- <li><%= link_to "Sign in", signin_path %></li> -->
             <li><%= link_to "Sign in ", "/signin"  %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    

  </head>
 
 
    <body>
   
        <%= render 'layouts/header' %>
    <div class="container">
    	<p class= "notice">
    		 <%= notice %></p> 
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    
      
    </div>
  </body>
</html>